"""empty message

Revision ID: 19fd1c378e8c
Revises: 1f86be80f9f5
Create Date: 2016-01-13 08:02:51.744356

"""

# revision identifiers, used by Alembic.
revision = '19fd1c378e8c'
down_revision = '1f86be80f9f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=10000), nullable=True),
    sa.Column('writer', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    ### end Alembic commands ###
