"""empty message

Revision ID: 3de99ed3f052
Revises: 19fd1c378e8c
Create Date: 2016-01-14 06:41:14.239683

"""

# revision identifiers, used by Alembic.
revision = '3de99ed3f052'
down_revision = '19fd1c378e8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('bad', sa.String(length=100), nullable=True))
    op.add_column('board', sa.Column('count', sa.String(length=100), nullable=True))
    op.add_column('board', sa.Column('good', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'good')
    op.drop_column('board', 'count')
    op.drop_column('board', 'bad')
    ### end Alembic commands ###
