"""empty message

Revision ID: 6959ece86cd5
Revises: e92e5034078b
Create Date: 2016-01-14 08:44:18.595959

"""

# revision identifiers, used by Alembic.
revision = '6959ece86cd5'
down_revision = 'e92e5034078b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('bad', sa.Integer(), nullable=True))
    op.add_column('board', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('board', sa.Column('good', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'good')
    op.drop_column('board', 'count')
    op.drop_column('board', 'bad')
    ### end Alembic commands ###
