"""empty message

Revision ID: e92e5034078b
Revises: f8dd8b2483b6
Create Date: 2016-01-14 07:43:29.366575

"""

# revision identifiers, used by Alembic.
revision = 'e92e5034078b'
down_revision = 'f8dd8b2483b6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('num', sa.Integer(), nullable=True))
    op.drop_column('board', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.drop_column('board', 'num')
    ### end Alembic commands ###
