"""empty message

Revision ID: f8dd8b2483b6
Revises: 3de99ed3f052
Create Date: 2016-01-14 07:39:33.734218

"""

# revision identifiers, used by Alembic.
revision = 'f8dd8b2483b6'
down_revision = '3de99ed3f052'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('id', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'id')
    ### end Alembic commands ###
